import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Hero from '@/components/hero'
import CustomerReviews from '@/components/customer-reviews'
import ProductLists from '@/components/products-list'
import AllProducts from '@/components/all-products'
import ShopByGrowers from '@/components/shop-by-growers'
import AllCategories from '@/components/all-categories'
import AllEvents from '@/components/all-events'
import { request  } from '../../lib/datocms'
import Divider from '@/components/divider'
import SocialCTA from '@/components/social-cta'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ data }) {
  const { hero, socialCtas } = data;
  console.log(data)
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Hero heading={ hero[0].heading } ctaTitle={ hero[0].ctaTitle } image={ hero[0].image }/>
        <SocialCTA datas={ socialCtas } />
        <Divider num={ 12 } />
        <CustomerReviews />
        <Divider num={ 12 } />
        <ProductLists />
        <Divider num={ 12 } />
        <AllCategories />
        <Divider num={ 12 } />
        <AllProducts />
        <Divider num={ 12 } />
        <ShopByGrowers />
        <Divider num={ 12 } />
        <AllEvents />
        <Divider num={ 12 } />
      </>
    </>
  )
}

export async function getStaticProps() {
  const HERO_QUERY = `
    query Hero {
      hero: allHeros(filter: {heading: {eq: "Finest Crafty Buds"}}) {
        heading
        ctaTitle
        image {
          responsiveImage(imgixParams: {fit: fill, auto: format}) {
            srcSet
            webpSrcSet
            sizes
            src
            width
            height
            aspectRatio
            alt
            title
            base64
          }
          url
        }
      }
      socialCtas: allHeros(filter: {heading: {notMatches: {pattern: "Finest Crafty Buds"}}}) {
        heading
        ctaTitle
        image {
          responsiveImage(imgixParams: { fit: fill, auto: format }) {
            srcSet
            webpSrcSet
            sizes
            src
            width
            height
            aspectRatio
            alt
            title
            base64
          }
          url
        }
      }
    }`
  ;
  const data = await request({ query: HERO_QUERY });

  return {
    props: { data }
  }
}
